// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViljaladuMVC.Data;

namespace ViljaladuMVC.Migrations
{
    [DbContext(typeof(ViljaladuDbContext))]
    partial class ViljaladuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ViljaladuMVC.Models.Koorma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AutoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LahkumisMass")
                        .HasColumnType("int");

                    b.Property<int>("SisenemisMass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Koormad");
                });
#pragma warning restore 612, 618
        }
    }
}
